# Site settings
title: Media @ Secret Escapes
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Our core goal is to inspire and motivate our members to experience unforgettable travel around the world. Our discerning, global audience comes to us precisely for such inspiration, through the beautiful and luxurious hotels we offer and the in-the-know content we create. We can put your brand front and centre of this conversation, allowing you to speak directly to our members.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/media-sales" # the subpath of your site, e.g. /blog/
img:     "/media-sales/_assets/img"
css:     "/media-sales/_assets/css"
js:      "/media-sales/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed